runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /admin(/.*)?
  script: main.app
  login: admin

- url: .*  # This regex directs all routes to main.app
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: "2.6"

skip_files:
- ^(.*/)?.*\.pyc$
- ^(.*/)?.*\.xcf$
